Tidy up dexter
gini/dexter pull request #53
Opened 2024-10-16 08:29 UTC by danielpodwysocki-gini

WIP - will correct this description and PR title once this branch builds cleanly.

2024-10-17 12:03 UTC, s-winkelhofer requested changes
When changing the release process, I would also suggest to include release names of the shape `0.0.0-rc.0`. We do the same for fedora-coreos-config to test release candidates on feature branches, before merging them and creating a final release (without `-rc.0`). That can be used as blueprint also for other repos such as the ops-infra-operator 

Do you plan to merge the dependabot PRs for version upgrades?

2024-10-17 12:09 UTC, danielpodwysocki-gini commented
> When changing the release process, I would also suggest to include release names of the shape `0.0.0-rc.0`. We do the same for fedora-coreos-config to test release candidates on feature branches, before merging them and creating a final release (without `-rc.0`). That can be used as blueprint also for other repos such as the ops-infra-operator

I'll get that added to the CI.

> That can be used as blueprint also for other repos such as the ops-infra-operator

I'd propose to keep those CI specs in a central place and import them - I maintained a similar workflow in the past and it saved a lot of time duplicating work across projects + allowed developers with little CI (or Go toolchain) experience to use them out of the box. 

It works really well together with a template repo for projects to use as a starting point - we could start one internally (this repo is public-facing), but that's a sidenote outside the scope of this.


> Do you plan to merge the dependabot PRs for version upgrades?

Yes. I will then build locally, test the resulting binary works and push a release tag once that's all looking right.

2024-10-17 12:25 UTC, danielpodwysocki-gini commented
@s-winkelhofer 
Updated the PR, allowing releasing from any branch and supporting rc tags.

2024-10-21 15:31 UTC, s-winkelhofer approved these changes

2024-10-21 15:48 UTC, merged